---
title: "Материалы"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
---
# Теория вероятностей и математическая статистика

<a href="https://drive.google.com/drive/folders/14o2pmWw_KsUzGaYspwqJB20ck_Ag_yfW?usp=sharing" title=>Ссылка на общую папку с литературой</a>  
Папка будет пополняться в процессе изучения материала.


### Обозначения

`r  shiny::icon("scroll")` -- семинарский листочек / решение 

`r  shiny::icon("readme")` -- Reading

`r  shiny::icon("desktop")` -- материалы для практикума (данные, код)

`r  shiny::icon("pencil")` -- задание

`r  shiny::icon("film")` -- видео-материал
 
## Занятие 1
 
Тема: повторение, дискретные сл.в. и их распределения, таблица совместного распределения, условное мат. ожидание

`r  shiny::icon("scroll")` <a href="tvims2_seminar1_2022.pdf" title=>Семинар 1</a>

`r  shiny::icon("pencil")` <a href="tvims2_hw1_2022.pdf" title=>Домашнее задание 1</a>

## Занятие 2
 
Тема: условное мат. ожидание, ATE (average treatment effect), распределение Пуассона

`r  shiny::icon("scroll")` <a href="tvims2_seminar2_2022.pdf" title=>Семинар 2</a>

`r  shiny::icon("pencil")` <a href="tvims2_hw2_2022.pdf" title=>Домашнее задание 2</a>

`r  shiny::icon("readme")` Mayer, 2011; Pianzola et al., 2019

## Занятие 3
 
Тема: ATE (average treatment effect), обсуждение, как в исследовании можно представить результаты эксперимента

`r  shiny::icon("scroll")` <a href="tvims2_seminar3_2022.pdf" title=>Семинар 3</a>

`r  shiny::icon("pencil")` <a href="tvims2_hw3_2022.pdf" title=>Домашнее задание 3</a>

`r  shiny::icon("film")` <a href="https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/resources/clip-1-introduction-to-definite-integrals/" title=>Introduction to Definite Integrals</a>  

## Занятие 4

Тема: экспоненциальное распределение

`r  shiny::icon("scroll")` <a href="tvims2_bonus_solution.pdf" title=>Решение бонусных заданий</a>

## Занятие 5

Тема: проверочная работа, введение в MLE

`r  shiny::icon("scroll")` <a href="tvims2_seminar4_2022.pdf" title=>Семинар 4</a>

Домашнее задание к 23 октября:

`r  shiny::icon("pencil")` <a href="tvims2_hw.pdf" title=>ДЗ 1 (сдаваемое)</a>

## Занятие 6

Тема: MLE

`r  shiny::icon("scroll")` <a href="tvims2_seminar5_6_2022.pdf" title=>Семинары 5-6 </a>

## Занятие 7

Тема: MLE

## Занятие 8

Тема: хи-квадрат, связь с нормальным распределением, доверительный интервал для дисперсии

`r  shiny::icon("scroll")` <a href="tvims2_seminar7_2022.pdf" title=>Семинар 7 </a>

Домашнее задание: подготовиться к контрольной работе

<a href="tvims2_midterm_LO_2022.pdf" title=>Learning outcomes</a> 

<a href="tvims2_demo_midterm_2022.pdf" title=>Демо-версия</a> 

## Занятие 9

Тема: проверка гипотезы о равенстве дисперсий

`r  shiny::icon("scroll")` <a href="tvims2_seminar8_9_2022.pdf" title=>Семинары 8-9 </a>

Домашнее задание к 4 декабря:

`r  shiny::icon("pencil")` <a href="tvims2_hw2.pdf" title=>ДЗ 2 (сдаваемое)</a>


# Введение в многомерный статистический анализ

<a href="https://drive.google.com/drive/folders/1egbTlUbPNY87aTL6sxE2NH7b5LfHYX_2?usp=share_link" title=>Ссылка на общую папку с литературой</a>  
Папка будет пополняться в процессе изучения материала.

### Обозначения

`r  shiny::icon("scroll")` -- семинарский листочек / решение 

`r  shiny::icon("readme")` -- Reading

`r  shiny::icon("desktop")` -- материалы для практикума (данные, код)

`r  shiny::icon("pencil")` -- задание

`r  shiny::icon("film")` -- видео-материал
 
## Занятие 1
 
Тема: Организационные вопросы. Иерархический кластерный анализ: методы кластеризации количественных данных

`r  shiny::icon("scroll")` <a href="tvims3_intro.pdf" title=>Организационная презентация</a>

`r  shiny::icon("scroll")` <a href="CA_lecture01.pdf" title=>Конспект лекции</a>

`r  shiny::icon("scroll")` <a href="CA_seminar01.pdf" title=>Семинарский листок</a>

`r  shiny::icon("scroll")` <a href="CA_seminar01-solutions.pdf" title=>Решение</a>

`r  shiny::icon("readme")` глава из книги Джеймс Г. и др. «Введение в статистическое обучение с примерами на языке R» (разделы 10.3.2-10.3.3)

## Занятие 2
 
Тема: Большой практикум в R. Оценка качества кластеризации

`r  shiny::icon("scroll")` <a href="CA_seminar02.pdf" title=>Семинарский листок</a>

`r  shiny::icon("scroll")` <a href="CA_seminar02-solutions.pdf" title=>Решение</a>

`r  shiny::icon("desktop")` <a href="https://disk.yandex.ru/d/lpvJbnF6WK08xw" title=>Практикум 1</a>

`r  shiny::icon("desktop")` <a href="https://disk.yandex.ru/d/WTmeCFqaDWPFaA" title=>Практикум 2</a>

## Занятие 3
 
Тема: кластерный анализ (продолжение)

## Занятие 4
 
Тема: Парная линейная регрессия. Выведение МНК-оценок

`r  shiny::icon("scroll")` <a href="tvims3_reg_lecture1.pdf" title=>Конспект лекции</a>

`r  shiny::icon("scroll")` <a href="tvims3_reg_seminar1.pdf" title=>Семинарский листок</a>

`r  shiny::icon("scroll")` <a href="tvims3_reg_hw1.pdf" title=>Домашнее задание к семинару 10 февраля</a>

`r  shiny::icon("film")` <a href="https://www.youtube.com/watch?v=WwW8y5dZs80&list=PL-uRhZ_p-BM5ovNRg-G6hDib27OCvcyW8" title=>Mastering Econometrics with Joshua Angrist</a>

## Занятие 5
 
Тема: Парная линейная регрессия: практикум в R. Допущения модели линейной регрессии

`r  shiny::icon("desktop")` <a href="tvims3_reg_lab1.html" title=>Разбор практикума в R</a> 

`r  shiny::icon("scroll")` <a href="tvims3_reg_hw2_2023.pdf" title=>Сдаваемое ДЗ (до 20 февраля включительно)</a>

## Занятие 6
 
Тема: Условие экзогенности в регрессионной модели. Источники и последствия эндогенности

`r  shiny::icon("scroll")` <a href="tvims3_endogeneity.pdf" title=>Презентация Эндогенность</a> 

`r  shiny::icon("scroll")` <a href="tvims3_reg_seminar2.pdf" title=>Семинарский листок</a>

Домашнее задание к 3 марта: 

выполнить задание 2 из семинарского листочка и подготовиться к проверочной работе (все материалы для подготовки -- на вкладке "Важные даты")

## Занятие 7
 
Тема: Проверочная работа №1. Множественная регрессионная модель. спецификация модели, выведение формулы для получения оценок коэффициентов, разложение вариации, проверка гипотезы о незначимости модели в целом, F-статистика 

`r  shiny::icon("scroll")` <a href="tvims3_seminar3_2023.pdf" title=>Семинарский листок</a>

Домашнее задание к 10 марта: 

`r  shiny::icon("scroll")` <a href="tvims3_reg_hw4_2023.pdf" title=>Домашнее задание</a>

## Занятие 8

Тема: Мультиколлинеарность

## Занятие 9

Тема: Мультиколлинеарность (продолжение, практикум). Гетероскедастичность

`r  shiny::icon("desktop")` <a href="tvims3_lab2.R" title=>Код в R</a> 

`r  shiny::icon("desktop")` <a href="reg_lab2.dta" title=>reg_lab2.dta</a> 

## Занятие 10
 
Тема: Гетероскедастичность (продолжение, практикум)

`r  shiny::icon("desktop")` <a href="tvims3_reg_lab3.html" title=>Разбор практикума в R</a>

`r  shiny::icon("desktop")` <a href="tvims3_lab3.R" title=>Код в R</a> 

`r  shiny::icon("scroll")` <a href="tvims3_reg_seminar3.pdf" title=>Семинарский листок</a>

## Занятие 11
 
Тема: Нетипичные наблюдения. Проблемы устойчивости результатов регрессионного анализа

`r  shiny::icon("desktop")` <a href="tvims3_lab4.R" title=>Код в R</a> 

## Занятие 12
 
Тема: Проверочная работа. Модели с переменными взаимодействия 

## Занятие 13
 
Тема: Модели с переменными взаимодействия (продолжение)

`r  shiny::icon("scroll")` <a href="tvims3_seminar_inter.pdf" title=>Семинарский листок</a>

`r  shiny::icon("scroll")` <a href="tvims3_interactions_solution_2023.pdf" title=>Разбор заданий из семинарского листка</a>

`r  shiny::icon("desktop")` <a href="tvims3_lab5.R" title=>Код в R</a> 

## Занятие 16
 
Тема: Факторный анализ (разведывательный этап)

## Занятие 17
 
Тема: Факторный анализ (конфирматорный)

`r  shiny::icon("desktop")` <a href="tvims3_FA_lab.html" title=>Разбор практикума в R</a>

`r  shiny::icon("desktop")` <a href="tvims3_lab_FA.Rdata" title=>Данные </a> 